@DataBaseApi_HostAddress = http://localhost:5116


GET {{DataBaseApi_HostAddress}}/api/users/
Accept: application/json

###
POST {{DataBaseApi_HostAddress}}/api/users   
Content-Type:application/json

{
    "TelegramId":"9345297",
    "UserName":"boba",
    "Status":0
}

###

GET{{DataBaseApi_HostAddress}}/api/User/2
Accept: application/json

###
GET{{DataBaseApi_HostAddress}}/api/User/telegram/9345297
Accept: application/json

###

DELETE {{DataBaseApi_HostAddress}}/api/users/9

###

GET {{DataBaseApi_HostAddress}}/api/courses
Accept:application/json
###

POST {{DataBaseApi_HostAddress}}/api/courses
Content-Type:application/json

{
    "Number":5
}

###

GET {{DataBaseApi_HostAddress}}/api/Teachers/by-name?fullName=Савченко%20Анна%20Олександрівна
Accept:application/json

###

GET {{DataBaseApi_HostAddress}}/api/lessons?dayId=6

###

POST https://pib-botdb-api.fly.dev/login
Content-Type:application/x-www-form-urlencoded

{
    username:admin
    password:Admin@123
}

###
GET {{DataBaseApi_HostAddress}}/api/lessons

###